version: '3'

vars:
  ONTOLOGY_DIR: example-ontology
  TEST_GIT_USER_NAME: "Anonymous Person"
  TEST_GIT_USER_EMAIL: "anonymous@example.org"

tasks:

  validate:
    desc: Validate the syntax of all YAML files
    cmds:
      - find -name "*.yml" -exec python validate_yml.py {} \;

  clean:
    desc: Clean up working directory
    cmds:
      - rm -rf {{.ONTOLOGY_DIR}}

  test:
    desc: Create plugin with default answers and run check
    deps:
      - validate
      - clean
    vars:
      TEMPLATE_REVISION:
        sh: git rev-parse HEAD
    cmds:
      - copier copy --vcs-ref {{.TEMPLATE_REVISION}} --defaults -d 'project_name=Test Project' . {{.ONTOLOGY_DIR}}
      - git init {{.ONTOLOGY_DIR}}
      - cd {{.ONTOLOGY_DIR}} && git add .
      - cd {{.ONTOLOGY_DIR}} && git -c init.defaultBranch=main -c user.name="{{.TEST_GIT_USER_NAME}}" -c user.email="{{.TEST_GIT_USER_EMAIL}}" commit -m "init from template"
      - cd {{.ONTOLOGY_DIR}} && task ci cd
